### ISSUE TITLE
Inconsistent committee photo sizes

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#150] opened 2021-08-18 20:37 UTC
The photos of the committee members on /committee are quite inconsistent, Fatima & Mohammed and Leaf & Ryan's rows especially. I think this could be rectified by cropping the images into a more square ratio so it looks similar to the rest.

**Comment by AlexJBanks** [comment] 2021-08-19 13:13
duplicate of #140

**Closed by AlexJBanks** 2021-08-19 13:13 UTC
Labels: bug
