### ISSUE TITLE
Newsletter posts still have "Joining us in 2021?" banner at the top

### ISSUE THREAD

**Issue by codemicro** [CSSUoB/cssuob.github.io#496] opened 2023-09-28 17:41 UTC
![image](https://github.com/CSSUoB/cssuob.github.io/assets/25284325/04728993-d7f4-4f5c-9e6a-6df19fef8425)

**Comment by MattyTheHacker** [comment] 2023-09-28 17:42
duplicate of #438

**Closed by MattyTheHacker** 2023-09-28 17:42 UTC

**Comment by codemicro** [comment] 2023-09-28 17:43
whoops
